### ISSUE TITLE
Замечания по коду

### ISSUE THREAD

**Issue by FZambia** [MyTaskBot/HW-1#1]
[line35](https://github.com/TelegramTaskManagerBot/HW-1/blob/master/main.py#L35): `id` - встроенная (builtin) ф-я, нежелательно давать переменным имена, переопределяющие такие ф-ии

[line 54](https://github.com/TelegramTaskManagerBot/HW-1/blob/master/main.py#L54): не обязательно было писать настолько красивый вывод:) надеюсь, скопировали откуда-то или  хотя бы фан от программирования получили:)

[line 129](https://github.com/TelegramTaskManagerBot/HW-1/blob/master/main.py#L129): создание здесь кеша - оверкилл, вообще можно было идентифицировать все команды по имени и не вводить никакой id

[line 215](https://github.com/TelegramTaskManagerBot/HW-1/blob/master/main.py#L215) - не нужно называть переменные в Python camel case’ом. Таких мест много

Далее:

``` python
def teams_sort(teams):

    def sort_key(param):
        return param["score"];

    teams.sort(key=sort_key);
    teams.reverse()
    ...
```

Во-первых, точки с запятой лишние:) И можно переписать так (не обязательно, просто на заметку):

``` python
def teams_sort(teams):

    def sort_key(param):
        return -param["score"]

    teams.sort(key=sort_key)

    ...
```

[line 189](https://github.com/TelegramTaskManagerBot/HW-1/blob/master/main.py#L189): что это за `-2` и `-3` я так и не понял.

[line 219](https://github.com/TelegramTaskManagerBot/HW-1/blob/master/main.py#L219) - лишний `pass`.

Это из того, что бросилось в глаза. В целом программа работает как нужно, хотя можно было написать проще. Желательно поправить стилевые замечания - пока за стиль не снижаем, но в будущем планируем.

**Comment by eckertigor** [comment]
Исправили замечания по коду.

**Comment by FZambia** [comment]
@ekkertigor @Sych474 @alexanderzot 👍
